[pytest]
addopts = -p no:tmpdir -p no:cacheprovider
norecursedirs = .git .venv __pycache__ .pytest_cache* .pytest_tmp .pytest_cache_dir results/tmpdir results/cache_dir results submissions problems pytest-cache-files-*
